### ISSUE TITLE
3Dミニゲームを投稿する

### ISSUE THREAD

**Issue by Ziyuan-Cao** [Siv3D/Siv3D-Samples#4]
https://github.com/Ziyuan-Cao/siv_game

**Comment by Reputeless** [comment]
ありがとうございます。実際に遊んでみました！
Shadow シェーダを自作している / 複数言語対応するなど、遊びやすさや画面表現へのこだわりを感じました。

ご投稿いただいた作品は、動作に必要なファイル数、ファイルサイズ、コードの行数が多く、
「改造や再利用がしやすいサンプルを提供する」という Siv3D-Samples リポジトリでは、受け入れるのが難しいです。
部分的に改造すればコンパクトにできるかなと考えましたが、難しそうでした。
したがって、Siv3D-Samples への収録は見送りとなります。

しかし Siv3D における 3D / 複数言語対応プログラムの良い事例なので、ご自身の SNS や Siv3D Discord サーバで、このゲームを紹介してほしいと思っています。

今後、数百行規模のサンプルを作られましたら、ぜひご投稿いただければ幸いです。

**Comment by Ziyuan-Cao** [comment]
丁寧にご対応いただき、ありがとうございます！
Siv3Dが使いやすいのおかけで、アイデアを実装過ぎました。
改めてコメントありがとうございます。紹介のことを試してみます。
