### ISSUE TITLE
シンプルなヴァンパイアサバイバーライクなゲームの提案

### ISSUE THREAD

**Issue by fluffySheepInX** [Siv3D/Siv3D-Samples#8]
https://github.com/fluffySheepInX/OpenSiv3D_0.6.71_VS_Like

・言語選択、オプションなど簡単なシーンを含めたゲーム。
・プルリク時はBGMを除きます（著作権フリーを謳うAIサービス製のBGMですが、恐らく（というか確実に）規約にひっかかる
・体力やゲームオーバー処理はコード行数的に止めておきました。

これで問題無ければプルリクさせて頂きます。
よろしくお願いします。

**Comment by Reputeless** [comment]
ご投稿ありがとうございます！コードの共有は、コミュニティにとって大変有益です。

ただし、公式サンプルは主に教材や模範として利用されることを目的としているため、**厳格な基準とレビュー**が適用されます。ご理解ください。

提出いただいたコードには、いくつか改善が必要な箇所があります。すべてではありませんが、改善の手がかりとなるポイントを以下に挙げておきます。
- `counter++;` のようなフレームレートに依存するコードが含まれています。120Hz や 240Hz の環境で実行すると速度が 2 倍や 4 倍になります。時間ベースのコードに変更してください。参考として「チュートリアル 3.5 一定時間ごとに出現」が役立ちます。
  - 参考: https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-animation
- 342 行目と 425 行目の `DiscreteDistribution distribution;` が重複しており、どちらかが使用されていません。整理しましょう。
- BGM ファイルやボタン画像ファイルなど、試す際に追加ファイルが必要となる非本質的な部分は省いてください（ボタンは `SimpleGUI::Button()` で代用できます）。
- 敵の当たり判定を長方形ではなく円にすると、パフォーマンスが向上します。特に理由がなければ、円を採用してみてください。
- `Window::SetTitle(U"KyoryuFire-Ver0.1");` のような作品タイトルは含めないでください。
- コメントアウトされたコード（431 行目など）は削除してください。
- Siv3D のスタイルに従ってください。
  - `int` → `int32` に変更します。
  - private メンバ変数には `m_` プレフィックスを付けます。
  - `String` 型は空の文字列として初期化されるため、`= U""` は不要です。
  - `enum` の代わりに `enum class` を使います。
  - メンバ関数名は小文字で始めます。
  - `text += U"Go hunt";` のようなコードは、`+=` ではなく `=` が適切です。

毎月開催されている OpenSiv3D 実装会に参加すれば、口頭や画面共有でコードレビューを受けられ、公式サンプルとして採用される基準に近づくことができます。早期の採用を目指す場合は、ぜひ参加をご検討ください。

さらに、他の公式サンプルのコードも参考になると思います。特に、クラスの使用に関しては、クロンダイクのサンプルが近い雰囲気を持っています。

改善に取り組んでいただくことで、さらに素晴らしいサンプルコードへと発展することを期待しています。引き続き、コミュニティへのご貢献をどうぞよろしくお願いいたします。

**Comment by fluffySheepInX** [comment]
了解しました。ご指摘ありがとうございます。
改善に取り組んでみます。
